plugins:
  - jekyll-redirect-from
  - jekyll-org
  - jekyll-git_metadata

collections_dir: collections
collections:
  links:
    output: true
  thoughts:
    output: true
  terms:
    output: true
  moments:
    output: true
  questions:
    output: true
  symbols:
    output: true
  experiences:
    output: true
  sounds:
    output: true

defaults:
  - scope:
      type: "thoughts"
    values:
      layout: "long"
  - scope:
      type: "terms"
    values:
      layout: "short"
  - scope:
      type: "moments"
    values:
      layout: "moment"
  - scope:
      type: "questions"
    values:
      layout: "long"
  - scope:
      type: "experiences"
    values:
      layout: "long"
  - scope:
      type: "sounds"
    values:
      layout: "sound"

org:
  liquid: true
