plugins:
  - jekyll-redirect-from
  - jekyll-org
  - jekyll-git_metadata

collections:
  links:
    output: true
  thoughts:
    output: true
  terms:
    output: true
  moments:
    output: true
  questions:
    output: true

defaults:
  - scope:
      type: "thoughts"
    values:
      layout: "thought"
      subtitle: "a thought."
  - scope:
      type: "terms"
    values:
      layout: "term"
      subtitle: "a term."
  - scope:
      type: "moments"
    values:
      layout: "moment"
      subtitle: "a moment."
  - scope:
      type: "questions"
    values:
      layout: "question"
      subtitle: "a possible answer."
org:
  liquid: true
