plugins:
  - jekyll-redirect-from
  - jekyll-org
  - jekyll-git_metadata

collections:
  links:
    output: true
  thoughts:
    output: true
  terms:
    output: true
  moments:
    output: true

defaults:
  - scope:
      type: "thoughts"
    values:
      layout: "thought"
      subtitle: "a thought."
      subtitle_link: "/thoughts"
  - scope:
      type: "terms"
    values:
      layout: "term"
      subtitle: "a term."
      subtitle_link: "/terms"
  - scope:
      type: "moments"
    values:
      layout: "moment"
      subtitle: "a moment."
      subtitle_link: "/moments"
org:
  liquid: true
