plugins:
  - jekyll-redirect-from
  - jekyll-org
  - jekyll-git_metadata

collections:
  links:
    output: true
  thoughts:
    output: true
  terms:
    output: true
  moments:
    output: true
  questions:
    output: true
  symbols:
    output: true

defaults:
  - scope:
      type: "thoughts"
    values:
      layout: "thought"
  - scope:
      type: "terms"
    values:
      layout: "term"
  - scope:
      type: "moments"
    values:
      layout: "moment"
  - scope:
      type: "questions"
    values:
      layout: "question"

org:
  liquid: true
