#+TITLE: Memories in Relation to Conciousness
#+SONG: apathy
#+BANNER: awaken.gif
#+BANNER_HEIGHT: 60px

I feel like I remember very little. I think it's a problem, but the people I trust tell me in the nicest way that I'm probably being paranoid. And that's part of the problem really is that I can't really tell because well -- I can't remember.

* Memories

A large part of why I'm writing at all is as a way to have any form of my thoughts that actually stick around. As someone who suffers with cyclical thinking that drives my anxiety, it's probably for the best to have both an outlet in the moment and a place to reexamine in the future. At least attempt to not retread the same steps again for the trillionth time.

To be clear I mostly talking about long term memory, anything outside of what I would consider my current task. I'm a fairly single minded person when it comes to getting things done and as a result I'm not very good at context switching. But I'm mostly fine while working on the same thing throughout a day. Looking back on that same task is very difficult however. I think this also drives my obsessive nature when it comes to projects, it's how I've trained myself to get any positive feedback. That isn't exactly a unique characteristic to me or people with bad memory, but I wouldn't doubt it's heightened to some degree because of it.

Another clarifying point is that a lot of those memories that I would describe as /gone/ are still there, just not terribly accessible. It's very common to be with family or friends and have things triggered via a specific place, food, moment, etc. This is more common with larger events, such as travel. The real trouble comes with situations where nothing terribly of note happens, but I do need to remember it to complete something else.

* Critical Thinking

I often describe myself as someone who doesn't think a lot. Running on instincts, internally very emotional guided, but anytime I've had others describe me I'm logical and stoic. This could simply be a result of me not accepting how everyone else is running internally or I'm bad at examining how I protray myself. Another issue though is that I only ever really remember actions and events and not the internal mechanisms that get me there.

If I play back my life like a sequence of events from a third perspective there's no way to tell how much is intuitive and how much is critical. Which is spooky. If this wasn't something I kept in mind I assume it would be an easy trap to fall in. That is choosing to run on instincts since critical thinking is harder and still doesn't get you anywhere. Which is probably not the case, but fuck if I can remember.

* Self

The larger ongoing struggle is paradoxically about being present. Although memories, are well, in the past they do affect nearly everything I do in the present. And as I grow older and feel like I'm losing touch with my past, I also lose touch with what I'm doing at any given moment or for what reason. At moments I'll feel quite lost and mostly mentally floating, almost to the point of dissociation. Self-described as star dust in front of a computer screen.

Grounding strategies can be useful for situations like this, but I've personally found them inconsistent. Similar to positive reframing most of the gains are impossible to see and continuing to practice them is the only way to make progress. So shoutout to tasks with no positive feedback.

I'm probably paranoid, but fuck these SSRIs are not making this part easier.
