#+TITLE: Anger, Assertiveness, and Aggressiveness.
#+LAYOUT: post
#+SPOTIFY: 6NRJBauViiZyXUTUqBpgNe

I have been angry lately -- which sounds silly. Isn't everyone angry lately? Well either I've suddenly gotten angrier lately or I've become more aware of it because I'd say its been a while since I've been angry.

Since I'd say anger is a pretty normal and healthy emotion to experience -- I must not have a very positive relationship with anger. So I'll cover why I think that's the case in some kind of attempt to get it through my meat computer.

As with most things that I'm wrong about it comes down to an unrealistic view of the world. Some common factors that could cause my poor vision being bias, ignorance, and ego. I'll try to breakdown my issues into the defined categories, but they tend to all be intermingled and fulfill the others so... /oh well/

** Bias

Anger ain't so bad I guess, but it is almost never protrayed as such. This is probably mostly a result that visual representations are easier to precieve then internal/mental representations. Whether it's real life or in some other medium anger is mostly seen as the physical side effects. Punching walls, yelling, etc. But anger begins as an internal energy created due to an injustice (whether it is actually injustice is another question). The powerful thing about anger is that you are in a much more actionable state. Thus the physical side effects, which are visceral and memorable leading to a bias of what anger really is. However this actionable state can be used for positive change as well. It's just worth keeping in mind.

** Ignorance

I think a fundamental misunderstanding can be caused just by the fact that language can sometimes be limited. Even something as core as emotion can be misconstrued very easily, since we are so dependent on the information we are given from others. In this case I think its quite easy to mistake anger for either assertive or aggressive in both a linguistic or cultural sense. To try and remedy this I wrote my own definitions:

/anger/
> Unmanaged energy in response to an event

/assertive/
> Confident action

/aggressive/
> Action in spite of another

These definitons are 100% incorrect, but there is no way you can make me research literally anything.

** Ego

The largest symptom of the natural bias of physical anger is it's association with specific personal characteristics. For example, the lady that can't help but start an argument with the walmart greeter I would describe as an angry person. Considering I'm a very passive person and have an aversion to high ego personalities I would assume there's a correlation with anger and high ego. Since anger is the energy build up, the only high ego part of my example is the reaction. Which is just like every other emotion. Your moral status isn't effected by your emotions, but your actions have consequences (it only took me 25 years to get it Mom sorry). I guess the /great/ irony is that my opinion on anger was the real high ego choice of it all.

I'd still like to be angry less it's hard.
