#+TITLE: Cowboys, Capital, Communes, Cabins.
#+LAYOUT: post
#+SPOTIFY: 7qe1VbsnzwQIKBTj9C1FTn

Probably as a side effect of obsession and identity I somehow always come up with long term end games. Like a self inflicted job interview I take every couple of months, except I only ask where I'm gonna be in 20 years.

For the most part it's kinda fun if you don't think about it too hard. The grass is greener and all that. Try to think of a scenario that the current you has never experienced, maybe that'll save your existence and you just don't know it yet.

Lately I've wanted to be a cowboy.

Which doesn't really make sense. I'd love to have a pair and a 10 gallon, but I'm not exactly looking to start an armed robbery or the modern equivalent drinking their life away at a shitty dive bar. It's all aethsetics in the least practical way possible.

What's become pretty clear to me is that I don't really make plans -- I'm terrible at it. The greatest leading factor of circular thinking; a result of future possibilities. Then how do I plan on getting the mental equivalent of a dollar tree sherrif's badge? Surely that's a "plan".

Instead I'd argue that goals don't define where you end up at all. This isn't to say your choices have no effect, but the choice to become something or be somewhere when you have so little knowledge of that time is so trivial. It would be silly to say that I knew, for one, who and where I would want to be in 20 years, but secondly how I would be able to accomplish that in 20 years. I feel like I'm completly different human then the one 4 years ago -- literally (or maybe thats just my "memories").

What really defines who I am in the future is based on many small choices I make with no direct relation to longterm strategy or planning. Like the butterfly effect, but for real decisions that you can actually measure. Metrics defined by attitude.

** Values/Metrics

So what do I put in the soup for Jim Sullivan to simmer? More importantly where does a cowboy fall in my mental model of things to be. Because if you have somehow read to this point, you've learned that nothing I think about can be genuine or real apparently.

The current human typing this thinks most of his decisions come down to two factors:

1. Ego
2. Isolation

The thought of being a cowboy probably came up as a result of recent life events, but only really latched too my melting brain as it can be well defined by these forces. A high ego, high isolation concept. Playing for self, outside society.

** Charting

One of the beauties of oversimplification is how easy it is to visulize. When working two easily defined vectors we can make a nice chart for the purpose of plotting.

| + I - E | + I + E |
| - I - E | - I + E |

Given how I described my cowboy earlier he would fit in our top right quadrent.

| ⠀ | 🤠 |
| ⠀ | ⠀   |

Simple.

To contrast it we can compare to some other mental aesthetics:

1. Capital gains
2. Communal living
3. The ill defined druid/hermit that only spends times with animals and maybe bakes(?)

| 🍞 | 🤠 |
| 🏘 | 💰 |

This example makes it pretty clear, which is why I came to this charting conclusion in the first place.

** Decision Making

So if you wanted to get something practical out of this, unlike me, I would consider the following things:

1. What core forces define your everyday life
2. What side of the spectrum do you align with,
3. ...?
4. Continue to /not/ profit in the year of our lord because you are listening to advice I don't even follow

If you are anything like me, life mostly consists of floating through space. Decisions are being made, but as a symptom of my current world view.

I wanna be a cowboy baby.
