#+TITLE: How should I represent myself online?

Having an online presence tends to be against my ongoing incentives. The modern internet, like most things, encourages us to behave in ways that are against our best interest. Both individually and as a community.

But for some reason I really wanted to write stuff down, put a song on it, and share it with friends. Which there wasn't an obvious way to do on the many, many, many platforms that already exist.

I had already hosted a static, single page site on [[https://github.io][github]] using [[https://jekyllrb.com][jekyll]], but it was essentially just an excuse to use my cosmetic url [[https://lllil.li][lllil.li]] (a very worthwile ongoing purchase).

The feature list included:

- an image generated by [[symbols]]
- my email crossed out
- a page for the git commit
- a 404 page
- a [[https://github.com/comfies/circle][webring]] embed

Well the first change is obvious. We need to modernize:

{% include question-item.html question_name='dark' %}

Next I'd need to structure how exactly I wanted these /posts/ to look (And also add a cowboy typing on a computer):

{% include question-item.html question_name='thoughts' %}

I found simply only using posts a bit frustrating. It's a pretty common practice to just use tags or categories to seperate out functionally different writing, but this leads to the same UI/UX experience for both the reader and writer even when the writing could vary greatly in length and goal.

Unfortuantly I've come up with ---

{% include question-item.html question_name='moments' %}

blahyyj

{% include question-item.html question_name='questions' %}

blahyyj
