#+TITLE: Measuring self
#+LAYOUT: post

I fucking love metrics. They make life easier. I hear a lot of people talk about how staticians never see the whole picture, when in reality they can only work with what they have. As technologies improve data becomes more descriptive and as a result more consistent predictions can be made. It's great! Unless you are bad at stats like me.

One of my greatest failures as an amateur statistician is measuring my self:

1. I collect the worst quality data about myself
2. I cannot seperate my own biases about myself from the data
3. The metrics that I think are important about myself are actually terrible at predicting things

I know this because I'm literally wrong all the time about myself -- and everything else.

** Internal Mental State

I like to think I know what's going on with my friends and family. But if I had to really ask myself I know fucking nothing. There is no way for me to possible compare how am I currently doing mentally compared to someone else except for the knowing how they talk about it in relation to their physical symptoms of their mental health. In other words its very hard and I'm not a professional. Without this context it makes it quite difficult to tell what is exactly /normal/ mentally. I don't mean in a, "boy is he strange" kind of normal. I'm more worried about things that may or may not cause harm at some point and I'm not currently concerned about.

In relation to metrics, it's bad data both for its terrible context and 

** Goals

Goals have always been what I imagined what you are supposed to have if want to be a person that actually does things. Makes sense as someone who doesn't make a lot of goals and also isn't a person who gets a whole lot of things done. But there is an obvious pattern in a lot of people, including myself, of a certain level of productivity porn. I think a lot of people would argue that something as simple as laying out goals can't possibly be distracting. Like come on, that's the whole fucking point right? However when I look back a goals that I actually achieved, they're almost never a result of good decision making. Or on the other end of the spectrum, the goal was terrible and not very useful as a metric.

What I'm suggesting here is that when you over value goals, you don't always achieve things that are actually productive. Maybe I'm just bad at making goals. They can be a terrible metric because they don't actually represent progress of improving as a human, only a possible symptom of it. However often goals can simply be met because of environment or circumstance.

Instead I would suggest (mainly as a reminder to myself) that real value is found in process and habit. And yes you can make a goal to have a habit, but that's where the real dilema begins for me. Goals suggest something to be completed as apposed to something you can pick up or maintain. Semantics, but I think the mental clarification can be valuable.

** Time

---

God I'm bad at math
