#+TITLE: Sports, History, and How to Share too Much
#+SPOTIFY:
#+BANNER:

History is hard and long and complex -- [[/thoughts/small][Anti-small]]

So when it comes to sweeping geo-political eras and they're consequences, I can't keep up.

I've given [Dan Carlin] another try and while his delivery is like a shakespearean narrator it didn't make the idea of the Ninevites having to defend against a completley mounted army (which clearly changed military strategy forever) all that compelling.

Seems pretty reasonable. I don't have the attention span for his specific format, this specific point in history isn't of that much interest, I'm not too interested in military exploits.

However I'm just gonna use this as an excuse to talk about something I do particularly enjoy. Although self indulgent, it's gotta be a better use of my time then to find out how to like something.

Sports

Sports is many things unfortunatly. I have no idea how most of them work.

When I was 6 I took my first skating lessons. I fell, I cried, I left.
When I was 9 I joined a softball team. I pitched, I cried, I left.
When I was 13 I joined a curling team. I think I mostly just cried.

Luckily sports are mostly not about actively participating in them. They're for nerds and wannabes.

While playing casual sports may have many positive upsides, the actual output of sports cultural impact is substantially engulfed in the consumption of professional sports. And with such a level of importance in the modern landscape, you also get the obssevies, the archivists, and story tellers. Just like any other niche in human history. Tales of conquerers, of underdogs, and evolution.

But what sets apart sports from traditional historical book keeping, is the thorough avaliability of statistics. Only possible because we enjoy watching peak athletic humans do the same mundane tasks a hundred times a year since the beginning of the modern era.

** Stats

// Something about finding anomoly, or outside of regular distribution.

// Connor McDavid stuff blah blah

// Derive someone maybe?

** Individuals

So often the winners get to write history, and that's not to say sports is exampt to this. Teams with historic wins and success tend to be favored when it comes to talking about legacy, I find that the true beauty with the use of stats is that you can find the individuals.

Stories of how people handle unfortunate circumstance, but not for the sake of how they turn it around. Seeing the stories of humans who have reached a level of percantile unimaginable stuck in limbo for their entire career simply because of where they were drafted. Life is full of uncontrolled environments that decide your life.

// TIE TOGETHER THE USE OF STORY BEING AMPLIFIED BY RESULTS AND STATS



