#+TITLE: ??????
#+SPOTIFY: 
#+BANNER: 

Time a tumblin', me a mumblin'.

The usual.
So the synapses are firing right, like the digital ones. Ya know? Theres the one that beat Jennings right? Or like the chess one, uhhh big blue?

{% include scroll.html content='Multiple times while writing I had to catch myself from personifying the AI using terms like, dude, homie, etc. Take that as you will.' %}

Say we don't all die as an invetability. Wild.

What the Fuck are we gonna do?

Well I don't really want to talk about that. Because I don't care and it's not that interesting to me. We'll figure it out. However this train usually choo choos to /art/ station. Right down the /art/ canyon. But what do people mean by that even? Here are some things that people suggest doing when are your needs are met:

+ Make music
+ Paint something
+ Maybe like the macaroni thing where ya glue it in the shape of your lost father figure?

But I can do that now. And you know what people talk about doing now? Reversing time, coming to our senses, hang out with the chimps. I mean they taught me how to open bananas correctly so how smart can I be?

I guess the question I'm really asking is not what is art. Because I hate that, but why. Like what was the utility of caveman paintings? Teaching? Historical? Decor? Are we day one out the slime looking for an outlet?

Art tends to have strong associations with the extensialism, trite shit like existence. Are humans just climbing that pyramid? Not the food one.

Maybe there's a reversal of art in a similar vain. Not in execution necessasrily, but in utility. The equivalent of fending for yourself in an expressive landscape.



